var files_dup =
[
    [ "asprintf.h", "asprintf_8h_source.html", null ],
    [ "clodo_loop.c", "clodo__loop_8c.html", "clodo__loop_8c" ],
    [ "compile_program.h", "compile__program_8h_source.html", null ],
    [ "cpu.h", "cpu_8h.html", "cpu_8h" ],
    [ "debug.h", "debug_8h.html", "debug_8h" ],
    [ "display.h", "display_8h_source.html", null ],
    [ "dmg_boot_rom.h", "dmg__boot__rom_8h.html", "dmg__boot__rom_8h" ],
    [ "ext_op.h", "ext__op_8h_source.html", null ],
    [ "fallback_debugger.h", "fallback__debugger_8h.html", "fallback__debugger_8h" ],
    [ "gb.h", "gb_8h.html", "gb_8h" ],
    [ "gbmu.h", "gbmu_8h.html", null ],
    [ "glerr.h", "glerr_8h_source.html", null ],
    [ "input_functions.c", "input__functions_8c.html", "input__functions_8c" ],
    [ "input_functions.h", "input__functions_8h.html", "input__functions_8h" ],
    [ "lib.h", "lib_8h_source.html", null ],
    [ "mbc.h", "mbc_8h_source.html", null ],
    [ "memory.h", "memory_8h.html", "memory_8h" ],
    [ "mode.h", "mode_8h.html", "mode_8h" ],
    [ "op.h", "op_8h_source.html", null ],
    [ "ppu.h", "ppu_8h.html", "ppu_8h" ],
    [ "registers.h", "registers_8h.html", null ],
    [ "renderer.h", "renderer_8h_source.html", null ],
    [ "renderer_opengl.h", "renderer__opengl_8h_source.html", null ],
    [ "rescale.h", "rescale_8h_source.html", null ],
    [ "rom.h", "rom_8h.html", "rom_8h" ],
    [ "wrapper.h", "wrapper_8h_source.html", null ]
];