use num_enum::{IntoPrimitive, TryFromPrimitive};
use std::fmt;
/// RESET n, r8 | [HL]
/// Set bit n in register r8 or at address [HL] to 0.
///
/// Cycles: 8 | 16
///
/// Bytes: 2
///
/// Flags: None affected.

#[derive(Eq, PartialEq, TryFromPrimitive, IntoPrimitive, Clone, Copy)]
#[repr(u8)]
#[allow(clippy::upper_case_acronyms)]
pub enum Bitset {
    BBit0 = 0xC0,
    BBit1 = 0xC8,
    BBit2 = 0xD0,
    BBit3 = 0xD8,
    BBit4 = 0xE0,
    BBit5 = 0xE8,
    BBit6 = 0xF0,
    BBit7 = 0xF8,
    CBit0 = 0xC1,
    CBit1 = 0xC9,
    CBit2 = 0xD1,
    CBit3 = 0xD9,
    CBit4 = 0xE1,
    CBit5 = 0xE9,
    CBit6 = 0xF1,
    CBit7 = 0xF9,
    DBit0 = 0xC2,
    DBit1 = 0xCA,
    DBit2 = 0xD2,
    DBit3 = 0xDA,
    DBit4 = 0xE2,
    DBit5 = 0xEA,
    DBit6 = 0xF2,
    DBit7 = 0xFA,
    EBit0 = 0xC3,
    EBit1 = 0xCB,
    EBit2 = 0xD3,
    EBit3 = 0xDB,
    EBit4 = 0xE3,
    EBit5 = 0xEB,
    EBit6 = 0xF3,
    EBit7 = 0xFB,
    HBit0 = 0xC4,
    HBit1 = 0xCC,
    HBit2 = 0xD4,
    HBit3 = 0xDC,
    HBit4 = 0xE4,
    HBit5 = 0xEC,
    HBit6 = 0xF4,
    HBit7 = 0xFC,
    LBit0 = 0xC5,
    LBit1 = 0xCD,
    LBit2 = 0xD5,
    LBit3 = 0xDD,
    LBit4 = 0xE5,
    LBit5 = 0xED,
    LBit6 = 0xF5,
    LBit7 = 0xFD,
    HLBit0 = 0xC6,
    HLBit1 = 0xCE,
    HLBit2 = 0xD6,
    HLBit3 = 0xDE,
    HLBit4 = 0xE6,
    HLBit5 = 0xEE,
    HLBit6 = 0xF6,
    HLBit7 = 0xFE,
    ABit0 = 0xC7,
    ABit1 = 0xCF,
    ABit2 = 0xD7,
    ABit3 = 0xDF,
    ABit4 = 0xE7,
    ABit5 = 0xEF,
    ABit6 = 0xF7,
    ABit7 = 0xFF,
}

impl fmt::Display for Bitset {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            Bitset::BBit0 => write!(f, "SET B, Bit 0"),
            Bitset::BBit1 => write!(f, "SET B, Bit 1"),
            Bitset::BBit2 => write!(f, "SET B, Bit 2"),
            Bitset::BBit3 => write!(f, "SET B, Bit 3"),
            Bitset::BBit4 => write!(f, "SET B, Bit 4"),
            Bitset::BBit5 => write!(f, "SET B, Bit 5"),
            Bitset::BBit6 => write!(f, "SET B, Bit 6"),
            Bitset::BBit7 => write!(f, "SET B, Bit 7"),
            Bitset::CBit0 => write!(f, "SET C, Bit 0"),
            Bitset::CBit1 => write!(f, "SET C, Bit 1"),
            Bitset::CBit2 => write!(f, "SET C, Bit 2"),
            Bitset::CBit3 => write!(f, "SET C, Bit 3"),
            Bitset::CBit4 => write!(f, "SET C, Bit 4"),
            Bitset::CBit5 => write!(f, "SET C, Bit 5"),
            Bitset::CBit6 => write!(f, "SET C, Bit 6"),
            Bitset::CBit7 => write!(f, "SET C, Bit 7"),
            Bitset::DBit0 => write!(f, "SET D, Bit 0"),
            Bitset::DBit1 => write!(f, "SET D, Bit 1"),
            Bitset::DBit2 => write!(f, "SET D, Bit 2"),
            Bitset::DBit3 => write!(f, "SET D, Bit 3"),
            Bitset::DBit4 => write!(f, "SET D, Bit 4"),
            Bitset::DBit5 => write!(f, "SET D, Bit 5"),
            Bitset::DBit6 => write!(f, "SET D, Bit 6"),
            Bitset::DBit7 => write!(f, "SET D, Bit 7"),
            Bitset::EBit0 => write!(f, "SET E, Bit 0"),
            Bitset::EBit1 => write!(f, "SET E, Bit 1"),
            Bitset::EBit2 => write!(f, "SET E, Bit 2"),
            Bitset::EBit3 => write!(f, "SET E, Bit 3"),
            Bitset::EBit4 => write!(f, "SET E, Bit 4"),
            Bitset::EBit5 => write!(f, "SET E, Bit 5"),
            Bitset::EBit6 => write!(f, "SET E, Bit 6"),
            Bitset::EBit7 => write!(f, "SET E, Bit 7"),
            Bitset::HBit0 => write!(f, "SET H, Bit 0"),
            Bitset::HBit1 => write!(f, "SET H, Bit 1"),
            Bitset::HBit2 => write!(f, "SET H, Bit 2"),
            Bitset::HBit3 => write!(f, "SET H, Bit 3"),
            Bitset::HBit4 => write!(f, "SET H, Bit 4"),
            Bitset::HBit5 => write!(f, "SET H, Bit 5"),
            Bitset::HBit6 => write!(f, "SET H, Bit 6"),
            Bitset::HBit7 => write!(f, "SET H, Bit 7"),
            Bitset::LBit0 => write!(f, "SET L, Bit 0"),
            Bitset::LBit1 => write!(f, "SET L, Bit 1"),
            Bitset::LBit2 => write!(f, "SET L, Bit 2"),
            Bitset::LBit3 => write!(f, "SET L, Bit 3"),
            Bitset::LBit4 => write!(f, "SET L, Bit 4"),
            Bitset::LBit5 => write!(f, "SET L, Bit 5"),
            Bitset::LBit6 => write!(f, "SET L, Bit 6"),
            Bitset::LBit7 => write!(f, "SET L, Bit 7"),
            Bitset::HLBit0 => write!(f, "SET [HL], Bit 0"),
            Bitset::HLBit1 => write!(f, "SET [HL], Bit 1"),
            Bitset::HLBit2 => write!(f, "SET [HL], Bit 2"),
            Bitset::HLBit3 => write!(f, "SET [HL], Bit 3"),
            Bitset::HLBit4 => write!(f, "SET [HL], Bit 4"),
            Bitset::HLBit5 => write!(f, "SET [HL], Bit 5"),
            Bitset::HLBit6 => write!(f, "SET [HL], Bit 6"),
            Bitset::HLBit7 => write!(f, "SET [HL], Bit 7"),
            Bitset::ABit0 => write!(f, "SET A, Bit 0"),
            Bitset::ABit1 => write!(f, "SET A, Bit 1"),
            Bitset::ABit2 => write!(f, "SET A, Bit 2"),
            Bitset::ABit3 => write!(f, "SET A, Bit 3"),
            Bitset::ABit4 => write!(f, "SET A, Bit 4"),
            Bitset::ABit5 => write!(f, "SET A, Bit 5"),
            Bitset::ABit6 => write!(f, "SET A, Bit 6"),
            Bitset::ABit7 => write!(f, "SET A, Bit 7"),
        }
    }
}
