name: Generate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mattnotmitt/doxygen-action@v1
        with:
          doxyfile-path: "./doc/Doxyfile"
          working-directory: "."

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./pouet"